spring.application.name=kidzworld
port=8081
spring.data.mongodb.uri=mongodb+srv://ayushghodke:ayushghodke@cluster0.ljutn.mongodb.net/kidzworld?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.mapping.field-strategy=ignore
